### ISSUE TITLE
no associated item named `AccessDenies` found for type `CaptureError` in the current scope

### ISSUE THREAD

**Issue by velbharathi-a** [bryal/captrs#2]
![image](https://cloud.githubusercontent.com/assets/21169453/26529805/e8de8ede-43e4-11e7-8d8b-a542c55f9365.png)

Could not compile the Crate due to the above error. Seems like a typo. Please have a look. Thank you. :)

**Comment by bryal** [comment]
Thanks for reporting this. I've not used windows for awhile, so I haven't noticed the regressions.

I have access to a windows PC now, and I have noticed a few other bugs. I will fix this build error and some other bugs shortly!
