### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by v1rtl** [bryal/captrs#3]
I'm not familiar with Rust ecosystem

How should I install this?

**Comment by bryal** [comment]
I updated the README with instructions. Feel free to ask if you have any more questions.

**Comment by v1rtl** [comment]
@bryal thank you! is there any chance to get a prebuilt binary? in releases tab

or it's a bloat in this case?



##### I'm trying to find a good screen recorder for linux so that's how I found this repo

**Comment by bryal** [comment]
Oh sorry, I just spoke before thinking, so to speak. Haven't worked on this project for a while, so mixed it up with [Helion](https://github.com/bryal/Helion) in my head for a second.

This project is only a library, so installation and building binaries doesn't really make sense. This project only handles capturing the screen contents to RAM, not recording to disk or streaming to the web. I'm not sure what your use case is, but it sounds like you want [OBS](https://obsproject.com/). OBS is an open source project (GPLv2) for primarily streaming, but also recording screen capture. I've only used it a little, but it's very performant compared to the alternatives afaik. It works on all major platforms.

**Comment by v1rtl** [comment]
@bryal, yeah I use OBS currently

I looked for something smaller and with as nice UI, but everything else is shit

so I thought if this project is more than a library but a GUI app

I don't know Rust, but would be cool to see a GUI app with using this lib :)
