### ISSUE TITLE
capturer.geometry() returns (0, 0) on windows

### ISSUE THREAD

**Issue by monoclex** [bryal/captrs#4]
It's most likely due to these [two lines](https://github.com/bryal/captrs/blob/master/src/lib.rs#L78-L79)

**Comment by bryal** [comment]
Indeed I suppose that ought to considered a bug.

A `geometry` method should be added to `DXGIManager` in the [`dxgcap`](https://github.com/bryal/dxgcap-rs) crate. This method should retrieve the geometry of the DXGI duplicated output like is done [at these lines in dxgcap/src/lib.rs](https://github.com/bryal/dxgcap-rs/blob/a3f5d424b98360c81a75db64937937c099c07830/src/lib.rs#L367-L376). We could then use that method in the `#[cfg(windows)]` version of [`Capturer::geometry`](https://github.com/bryal/captrs/blob/094a948eedec548a4f56df6d156748ccb0d9624f/src/lib.rs#L95-L99), pretty much exactly like it's done [in the Linux version of `Capturer::geometry`](https://github.com/bryal/captrs/blob/094a948eedec548a4f56df6d156748ccb0d9624f/src/lib.rs#L101-L106).

I'm afraid I can't do something about this myself at current, as I no longer have any machines running Windows, so I wouldn't be able to actually test any implementation. If someone else wants to take a crack at this, please go ahead and submit a PR!

**Comment by pballandras** [comment]
Hey, I followed instructions, now I got a 1920, 1080 output on a monitor of exactly this size! Cool! Now I'll submit this in a PR.

**Comment by bryal** [comment]
@ItsTehStory Sorry for not replying earlier, I'll take a look right away.

**Comment by bryal** [comment]
Great! These changes are now up on crates.io in `dxgcap` version 0.2.4 and `captrs` version 0.3.1.
